# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "P1xQeV5xGlRbVdceL1WSX85Wb++lJ6oNzyTXtkudKHVTVFFGHI0ng2nieGzJUIupEeQ69SOWABSDIjaxzZD59uTfeM69iQQcmgJPvK+c2/azRSPhntGaVlUCu/ABPmDxpqta/w23xTQugI7J/usUP2/T0tCFJMGdTylLasng3ZUhQ7K696Qc678QwGH3jOBM502F0UiDwi9lyLE3CgiIEMaF+TbMx9NdhSkSL/zzwkqnNXNxTvkdB7Hsq81OJnwY37ce5lmZFpgONCFN7EIPRRfPh7cgnKdOOw4s65KVnCF7FTGXqKH3UO/81IAzcwTEH/VB+YcAV4Lxx+oQMw7GyLwf7INmcDnmU8YT7E3VCPdmx0DYOi+wnHOFFBIMkQTsmyN7N98k142se+sPZTD8iiqsX4T/L6h6ogohxPz+0X2I+ukoGs4RRgehOj2i7l3rzNqDE64BaEEfAxhJfg16ANqgzbQip9pxpZZ4mI7GwQCYVaLWjGnEux8L/17PHqgQptCz43KDQ4Kw+7h1hattxXBHH6zFQf4Ba/79TJlXG0z9NXlwUylQvvOeUJ2n06YGMuIS2JOy9CFxU4IQ3uHcRQGDa99bYOaKN0iPb03i4jJ5A6NKxy6yQBo4ny9gvEBDQhvsAcCCXHhPfzqUbKX412VKaBAvMUGQpz8GyQbiKo0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
